from pydantic import BaseModel, Field


class Todo(BaseModel):
    """Representation of a to-do item which is retrieved from the database."""
    id: int = Field(description="The unique identifier of the to-do item")
    item: str = Field(description="Description of the to-do item")
    completed: bool = Field(description="Status of the to-do item whether it is completed or not")


class TodoIn(BaseModel):
    """
    Representation of a to-do item which is to be created or updated.
    ID is not required as it is auto-generated by the database.
    """
    item: str = Field(description="Description of the to-do item")
    completed: bool = Field(description="Status of the to-do item whether it is completed or not")
